apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdemo
  labels:
    app: appdemo
spec:
  selector:
    matchLabels:
      app: appdemo
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: appdemo
    spec:
      containers:
      - name: appdemo
        image: 152512582646.dkr.ecr.us-east-2.amazonaws.com/repo-app-sebas:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000