apiVersion: v1
kind: Service
metadata:
  name: appdemo
  labels:
    app: appdemo
spec:
  selector:
    app: appdemo
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
    name: appdemo